Class HCC.SVR.Prod.MSG.HIPMessageServerResponse Extends Ens.Response [ ProcedureBlock ]
{

Property HIPMessageServerResult As %String;

Storage Default
{
<Data name="HIPMessageServerResponseDefaultData">
<Subscript>"HIPMessageServerResponse"</Subscript>
<Value name="1">
<Value>HIPMessageServerResult</Value>
</Value>
</Data>
<DefaultData>HIPMessageServerResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
