/// 艾滋宿忠者亲属HⅣ感染状况代码表
Class WS.VS.CV0300404 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.1.40";

Storage Default
{
<Data name="CV0300404DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.CV0300404</DataLocation>
<DefaultData>CV0300404DefaultData</DefaultData>
<IdLocation>^WS.VS.CV0300404</IdLocation>
<IndexLocation>^WS.VS.CV0300404I</IndexLocation>
<StreamLocation>^WS.VS.CV0300404S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
