/// 艾滋病患者亲属HIV感染状况代码袁
Class WS.VS.CV0300004 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="CV0300004DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.CV0300004</DataLocation>
<DefaultData>CV0300004DefaultData</DefaultData>
<IdLocation>^WS.VS.CV0300004</IdLocation>
<IndexLocation>^WS.VS.CV0300004I</IndexLocation>
<StreamLocation>^WS.VS.CV0300004S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
