/// 伤害部位代码表
Class WS.VS.CV0410016 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.1.70";

Storage Default
{
<Data name="CV0410016DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.CV0410016</DataLocation>
<DefaultData>CV0410016DefaultData</DefaultData>
<IdLocation>^WS.VS.CV0410016</IdLocation>
<IndexLocation>^WS.VS.CV0410016I</IndexLocation>
<StreamLocation>^WS.VS.CV0410016S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
