/// 血吸虫患者肝实质纤维化程度代码表
Class WS.VS.CV0430001 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.1.77";

Storage Default
{
<Data name="CV0430001DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.CV0430001</DataLocation>
<DefaultData>CV0430001DefaultData</DefaultData>
<IdLocation>^WS.VS.CV0430001</IdLocation>
<IndexLocation>^WS.VS.CV0430001I</IndexLocation>
<StreamLocation>^WS.VS.CV0430001S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
