/// 随访方式代码表
Class WS.VS.CV0600207 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.1.183";

Storage Default
{
<Data name="CV0600207DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.CV0600207</DataLocation>
<DefaultData>CV0600207DefaultData</DefaultData>
<IdLocation>^WS.VS.CV0600207</IdLocation>
<IndexLocation>^WS.VS.CV0600207I</IndexLocation>
<StreamLocation>^WS.VS.CV0600207S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
