/// 常住地类型代码
Class WS.VS.DE020100200 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE020100200DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE020100200</DataLocation>
<DefaultData>DE020100200DefaultData</DefaultData>
<IdLocation>^WS.VS.DE020100200</IdLocation>
<IndexLocation>^WS.VS.DE020100200I</IndexLocation>
<StreamLocation>^WS.VS.DE020100200S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
