/// 接入互联网方式代码
Class WS.VS.DE020102100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE020102100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE020102100</DataLocation>
<DefaultData>DE020102100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE020102100</IdLocation>
<IndexLocation>^WS.VS.DE020102100I</IndexLocation>
<StreamLocation>^WS.VS.DE020102100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
