/// 每月食用食物的频率类别代码
Class WS.VS.DE030004400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE030004400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE030004400</DataLocation>
<DefaultData>DE030004400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE030004400</IdLocation>
<IndexLocation>^WS.VS.DE030004400I</IndexLocation>
<StreamLocation>^WS.VS.DE030004400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
