/// 每周食用食物的频率类别代码
Class WS.VS.DE030004500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE030004500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE030004500</DataLocation>
<DefaultData>DE030004500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE030004500</IdLocation>
<IndexLocation>^WS.VS.DE030004500I</IndexLocation>
<StreamLocation>^WS.VS.DE030004500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
