/// 接触二手烟代码
Class WS.VS.DE030002500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE030002500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE030002500</DataLocation>
<DefaultData>DE030002500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE030002500</IdLocation>
<IndexLocation>^WS.VS.DE030002500I</IndexLocation>
<StreamLocation>^WS.VS.DE030002500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
