/// 劳作情况代码
Class WS.VS.DE030003800 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE030003800DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE030003800</DataLocation>
<DefaultData>DE030003800DefaultData</DefaultData>
<IdLocation>^WS.VS.DE030003800</IdLocation>
<IndexLocation>^WS.VS.DE030003800I</IndexLocation>
<StreamLocation>^WS.VS.DE030003800S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
