/// 关锁情况代码表
Class WS.VS.DE030001700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.2.30";

Storage Default
{
<Data name="DE030001700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE030001700</DataLocation>
<DefaultData>DE030001700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE030001700</IdLocation>
<IndexLocation>^WS.VS.DE030001700I</IndexLocation>
<StreamLocation>^WS.VS.DE030001700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
