/// HBVDNA定性检测结果
Class WS.VS.DE045000400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045000400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045000400</DataLocation>
<DefaultData>DE045000400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045000400</IdLocation>
<IndexLocation>^WS.VS.DE045000400I</IndexLocation>
<StreamLocation>^WS.VS.DE045000400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
