/// 乙肝抗病毒治疗的病毒学应答
Class WS.VS.DE045011200 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045011200DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045011200</DataLocation>
<DefaultData>DE045011200DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045011200</IdLocation>
<IndexLocation>^WS.VS.DE045011200I</IndexLocation>
<StreamLocation>^WS.VS.DE045011200S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
