/// 乳糜尿发作规律代码
Class WS.VS.DE040105700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE040105700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE040105700</DataLocation>
<DefaultData>DE040105700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE040105700</IdLocation>
<IndexLocation>^WS.VS.DE040105700I</IndexLocation>
<StreamLocation>^WS.VS.DE040105700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
