/// 透光试验结果代码
Class WS.VS.DE041019300 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE041019300DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE041019300</DataLocation>
<DefaultData>DE041019300DefaultData</DefaultData>
<IdLocation>^WS.VS.DE041019300</IdLocation>
<IndexLocation>^WS.VS.DE041019300I</IndexLocation>
<StreamLocation>^WS.VS.DE041019300S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
