/// 痛经程度代码
Class WS.VS.DE040107600 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE040107600DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE040107600</DataLocation>
<DefaultData>DE040107600DefaultData</DefaultData>
<IdLocation>^WS.VS.DE040107600</IdLocation>
<IndexLocation>^WS.VS.DE040107600I</IndexLocation>
<StreamLocation>^WS.VS.DE040107600S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
