/// 黄疸状况代码
Class WS.VS.DE041008700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE041008700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE041008700</DataLocation>
<DefaultData>DE041008700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE041008700</IdLocation>
<IndexLocation>^WS.VS.DE041008700I</IndexLocation>
<StreamLocation>^WS.VS.DE041008700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
