/// 血吸虫虫卵检查结果代码
Class WS.VS.DE045010700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045010700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045010700</DataLocation>
<DefaultData>DE045010700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045010700</IdLocation>
<IndexLocation>^WS.VS.DE045010700I</IndexLocation>
<StreamLocation>^WS.VS.DE045010700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
