/// 大便常规检测结果代码
Class WS.VS.DE045002100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045002100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045002100</DataLocation>
<DefaultData>DE045002100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045002100</IdLocation>
<IndexLocation>^WS.VS.DE045002100I</IndexLocation>
<StreamLocation>^WS.VS.DE045002100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
