/// 咽部检查结果代码表
Class WS.VS.DE041021400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.2.6";

Storage Default
{
<Data name="DE041021400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE041021400</DataLocation>
<DefaultData>DE041021400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE041021400</IdLocation>
<IndexLocation>^WS.VS.DE041021400I</IndexLocation>
<StreamLocation>^WS.VS.DE041021400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
