/// 受检者滴虫检测结果代码
Class WS.VS.DE045007900 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045007900DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045007900</DataLocation>
<DefaultData>DE045007900DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045007900</IdLocation>
<IndexLocation>^WS.VS.DE045007900I</IndexLocation>
<StreamLocation>^WS.VS.DE045007900S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
