/// 皮下脂肪异常代码
Class WS.VS.DE041013400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE041013400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE041013400</DataLocation>
<DefaultData>DE041013400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE041013400</IdLocation>
<IndexLocation>^WS.VS.DE041013400I</IndexLocation>
<StreamLocation>^WS.VS.DE041013400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
