/// 结核菌群检测结果代码
Class WS.VS.DE045003500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045003500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045003500</DataLocation>
<DefaultData>DE045003500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045003500</IdLocation>
<IndexLocation>^WS.VS.DE045003500I</IndexLocation>
<StreamLocation>^WS.VS.DE045003500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
