/// 脾肿大分级代码
Class WS.VS.DE043002900 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE043002900DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE043002900</DataLocation>
<DefaultData>DE043002900DefaultData</DefaultData>
<IdLocation>^WS.VS.DE043002900</IdLocation>
<IndexLocation>^WS.VS.DE043002900I</IndexLocation>
<StreamLocation>^WS.VS.DE043002900S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
