/// 伤害严重程度代码
Class WS.VS.DE040106300 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE040106300DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE040106300</DataLocation>
<DefaultData>DE040106300DefaultData</DefaultData>
<IdLocation>^WS.VS.DE040106300</IdLocation>
<IndexLocation>^WS.VS.DE040106300I</IndexLocation>
<StreamLocation>^WS.VS.DE040106300S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
