/// 乙型肝炎病毒核心抗体检测结果代码
Class WS.VS.DE045011700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045011700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045011700</DataLocation>
<DefaultData>DE045011700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045011700</IdLocation>
<IndexLocation>^WS.VS.DE045011700I</IndexLocation>
<StreamLocation>^WS.VS.DE045011700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
