/// 乙型肝炎病毒e抗原检测结果代码
Class WS.VS.DE045011400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045011400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045011400</DataLocation>
<DefaultData>DE045011400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045011400</IdLocation>
<IndexLocation>^WS.VS.DE045011400I</IndexLocation>
<StreamLocation>^WS.VS.DE045011400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
