/// 鞘膜积液累及部位代码
Class WS.VS.DE043003200 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE043003200DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE043003200</DataLocation>
<DefaultData>DE043003200DefaultData</DefaultData>
<IdLocation>^WS.VS.DE043003200</IdLocation>
<IndexLocation>^WS.VS.DE043003200I</IndexLocation>
<StreamLocation>^WS.VS.DE043003200S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
