/// 血吸虫病抗体检测结果代码
Class WS.VS.DE045010600 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE045010600DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE045010600</DataLocation>
<DefaultData>DE045010600DefaultData</DefaultData>
<IdLocation>^WS.VS.DE045010600</IdLocation>
<IndexLocation>^WS.VS.DE045010600I</IndexLocation>
<StreamLocation>^WS.VS.DE045010600S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
