/// 检查/检验结果代码表
Class WS.VS.DE043001506 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.2.38";

Storage Default
{
<Data name="DE043001506DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE043001506</DataLocation>
<DefaultData>DE043001506DefaultData</DefaultData>
<IdLocation>^WS.VS.DE043001506</IdLocation>
<IndexLocation>^WS.VS.DE043001506I</IndexLocation>
<StreamLocation>^WS.VS.DE043001506S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
