/// 淋巴管或淋巴结炎发作代码
Class WS.VS.DE050102800 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE050102800DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE050102800</DataLocation>
<DefaultData>DE050102800DefaultData</DefaultData>
<IdLocation>^WS.VS.DE050102800</IdLocation>
<IndexLocation>^WS.VS.DE050102800I</IndexLocation>
<StreamLocation>^WS.VS.DE050102800S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
