/// 产前筛查方法代码
Class WS.VS.DE051000800 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051000800DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051000800</DataLocation>
<DefaultData>DE051000800DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051000800</IdLocation>
<IndexLocation>^WS.VS.DE051000800I</IndexLocation>
<StreamLocation>^WS.VS.DE051000800S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
