/// 随访饮食合理性评价类别代码
Class WS.VS.DE051006700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051006700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051006700</DataLocation>
<DefaultData>DE051006700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051006700</IdLocation>
<IndexLocation>^WS.VS.DE051006700I</IndexLocation>
<StreamLocation>^WS.VS.DE051006700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
