/// 新生儿苯丙酮尿症筛查代码
Class WS.VS.DE051008500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051008500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051008500</DataLocation>
<DefaultData>DE051008500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051008500</IdLocation>
<IndexLocation>^WS.VS.DE051008500I</IndexLocation>
<StreamLocation>^WS.VS.DE051008500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
