/// 乙型肝炎肝硬化分期代码
Class WS.VS.DE051009600 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051009600DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051009600</DataLocation>
<DefaultData>DE051009600DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051009600</IdLocation>
<IndexLocation>^WS.VS.DE051009600I</IndexLocation>
<StreamLocation>^WS.VS.DE051009600S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
