/// 美国麻醉医师协会分级标准代码
Class WS.VS.DE051012900 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051012900DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051012900</DataLocation>
<DefaultData>DE051012900DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051012900</IdLocation>
<IndexLocation>^WS.VS.DE051012900I</IndexLocation>
<StreamLocation>^WS.VS.DE051012900S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
