/// 贫血分级代码
Class WS.VS.DE051005000 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051005000DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051005000</DataLocation>
<DefaultData>DE051005000DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051005000</IdLocation>
<IndexLocation>^WS.VS.DE051005000I</IndexLocation>
<StreamLocation>^WS.VS.DE051005000S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
