/// 孕产妇死亡省级评审结果代码
Class WS.VS.DE051010100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051010100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051010100</DataLocation>
<DefaultData>DE051010100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051010100</IdLocation>
<IndexLocation>^WS.VS.DE051010100I</IndexLocation>
<StreamLocation>^WS.VS.DE051010100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
