/// 健康状况代码
Class WS.VS.DE051003400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE051003400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE051003400</DataLocation>
<DefaultData>DE051003400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE051003400</IdLocation>
<IndexLocation>^WS.VS.DE051003400I</IndexLocation>
<StreamLocation>^WS.VS.DE051003400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
