/// 首次诊断血吸虫病依据代码
Class WS.VS.DE050104100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE050104100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE050104100</DataLocation>
<DefaultData>DE050104100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE050104100</IdLocation>
<IndexLocation>^WS.VS.DE050104100I</IndexLocation>
<StreamLocation>^WS.VS.DE050104100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
