/// 孕产妇死亡时间类别代码
Class WS.VS.DE060015300 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060015300DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060015300</DataLocation>
<DefaultData>DE060015300DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060015300</IdLocation>
<IndexLocation>^WS.VS.DE060015300I</IndexLocation>
<StreamLocation>^WS.VS.DE060015300S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
