/// 输血反应类型
Class WS.VS.DE060026500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060026500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060026500</DataLocation>
<DefaultData>DE060026500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060026500</IdLocation>
<IndexLocation>^WS.VS.DE060026500I</IndexLocation>
<StreamLocation>^WS.VS.DE060026500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
