/// 重性精神疾病患者干预类型
Class WS.VS.DE060017200 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060017200DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060017200</DataLocation>
<DefaultData>DE060017200DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060017200</IdLocation>
<IndexLocation>^WS.VS.DE060017200I</IndexLocation>
<StreamLocation>^WS.VS.DE060017200S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
