/// 职业健康档案建立情况代码
Class WS.VS.DE060015700 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060015700DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060015700</DataLocation>
<DefaultData>DE060015700DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060015700</IdLocation>
<IndexLocation>^WS.VS.DE060015700I</IndexLocation>
<StreamLocation>^WS.VS.DE060015700S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
