/// 受孕形式代码表
Class WS.VS.DE060026100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.2.44";

Storage Default
{
<Data name="DE060026100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060026100</DataLocation>
<DefaultData>DE060026100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060026100</IdLocation>
<IndexLocation>^WS.VS.DE060026100I</IndexLocation>
<StreamLocation>^WS.VS.DE060026100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
