/// 治疗情况分类代码
Class WS.VS.DE060005600 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060005600DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060005600</DataLocation>
<DefaultData>DE060005600DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060005600</IdLocation>
<IndexLocation>^WS.VS.DE060005600I</IndexLocation>
<StreamLocation>^WS.VS.DE060005600S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
