/// 慢性丝虫病患者照料形式代码
Class WS.VS.DE060007500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060007500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060007500</DataLocation>
<DefaultData>DE060007500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060007500</IdLocation>
<IndexLocation>^WS.VS.DE060007500I</IndexLocation>
<StreamLocation>^WS.VS.DE060007500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
