/// 疾病防控情况代码
Class WS.VS.DE060006400 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060006400DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060006400</DataLocation>
<DefaultData>DE060006400DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060006400</IdLocation>
<IndexLocation>^WS.VS.DE060006400I</IndexLocation>
<StreamLocation>^WS.VS.DE060006400S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
