/// 放射剂量监测档案建档情况代码
Class WS.VS.DE060002500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060002500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060002500</DataLocation>
<DefaultData>DE060002500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060002500</IdLocation>
<IndexLocation>^WS.VS.DE060002500I</IndexLocation>
<StreamLocation>^WS.VS.DE060002500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
