/// 宫内节育器取出情况代码
Class WS.VS.DE060003300 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060003300DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060003300</DataLocation>
<DefaultData>DE060003300DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060003300</IdLocation>
<IndexLocation>^WS.VS.DE060003300I</IndexLocation>
<StreamLocation>^WS.VS.DE060003300S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
