/// 婚检咨询指导结果代码
Class WS.VS.DE060004100 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060004100DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060004100</DataLocation>
<DefaultData>DE060004100DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060004100</IdLocation>
<IndexLocation>^WS.VS.DE060004100I</IndexLocation>
<StreamLocation>^WS.VS.DE060004100S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
