/// 安全护理代码表
Class WS.VS.DE060017800 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.2.52";

Storage Default
{
<Data name="DE060017800DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060017800</DataLocation>
<DefaultData>DE060017800DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060017800</IdLocation>
<IndexLocation>^WS.VS.DE060017800I</IndexLocation>
<StreamLocation>^WS.VS.DE060017800S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
