/// 开展学生常见病防治情况代码
Class WS.VS.DE060006500 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060006500DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060006500</DataLocation>
<DefaultData>DE060006500DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060006500</IdLocation>
<IndexLocation>^WS.VS.DE060006500I</IndexLocation>
<StreamLocation>^WS.VS.DE060006500S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
