/// 免疫类型代码
Class WS.VS.DE060008000 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE060008000DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE060008000</DataLocation>
<DefaultData>DE060008000DefaultData</DefaultData>
<IdLocation>^WS.VS.DE060008000</IdLocation>
<IndexLocation>^WS.VS.DE060008000I</IndexLocation>
<StreamLocation>^WS.VS.DE060008000S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
