/// 消毒剂加药方式代码
Class WS.VS.DE085000900 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE085000900DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE085000900</DataLocation>
<DefaultData>DE085000900DefaultData</DefaultData>
<IdLocation>^WS.VS.DE085000900</IdLocation>
<IndexLocation>^WS.VS.DE085000900I</IndexLocation>
<StreamLocation>^WS.VS.DE085000900S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
