/// 监测设备金额分类代码
Class WS.VS.DE085000200 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Storage Default
{
<Data name="DE085000200DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.DE085000200</DataLocation>
<DefaultData>DE085000200DefaultData</DefaultData>
<IdLocation>^WS.VS.DE085000200</IdLocation>
<IndexLocation>^WS.VS.DE085000200I</IndexLocation>
<StreamLocation>^WS.VS.DE085000200S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
