/// GB/T2261.1 性别码表
Class WS.VS.GBT22611 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript ]
{

Parameter Name = "GB/T2261.1 性别码表";

Storage Default
{
<Data name="GBT22611DefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Display</Value>
</Value>
<Value name="3">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.GBT22611</DataLocation>
<DefaultData>GBT22611DefaultData</DefaultData>
<IdLocation>^WS.VS.GBT22611</IdLocation>
<IndexLocation>^WS.VS.GBT22611I</IndexLocation>
<StreamLocation>^WS.VS.GBT22611S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
