/// 家庭关系代码表（GB/T 4761）
Class WS.VS.GBT47612008 Extends WS.VS.Base [ ClassType = persistent, Language = objectscript, Not ProcedureBlock ]
{

Parameter OID = "2.16.156.10011.2.3.3.8";

Storage Default
{
<Data name="GBT47612008DefaultData">
<Attribute>Display</Attribute>
<Structure>node</Structure>
<Value name="1">
<Value>Display</Value>
</Value>
</Data>
<Data name="descr">
<Attribute>Description</Attribute>
<Subscript>"Descr"</Subscript>
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>Description</Value>
</Value>
</Data>
<DataLocation>^WS.VS.GBT47612008</DataLocation>
<DefaultData>GBT47612008DefaultData</DefaultData>
<IdLocation>^WS.VS.GBT47612008</IdLocation>
<IndexLocation>^WS.VS.GBT47612008I</IndexLocation>
<StreamLocation>^WS.VS.GBT47612008S</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
