Class WS.DE.DE020106000 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Parameter Category = "人口学及社会经济学特征";

Parameter Description = "患者类型";

Parameter Format = "AN..50";

Parameter ValueSet;

Parameter WSDT = "S3";

Property Value;

Storage Default
{
<Data name="DE020106000State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE020106000State</State>
<StreamLocation>^WS.DE.DE020106000S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
