Class WS.DE.DE030001500 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV03.00.116");

Parameter Category = "健康危险因素";

Parameter Description = "妇女个人不良行为接触史代码";

Parameter Format = "N2";

Parameter ValueSet = "CV03.00.116";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE030001500State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE030001500State</State>
<StreamLocation>^WS.DE.DE030001500S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
