Class WS.DE.DE041023200 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV04.10.002");

Parameter Category = "体格检查";

Parameter Description = "子宫大小代码";

Parameter Format = "N1";

Parameter ValueSet = "CV04.10.002";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE041023200State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE041023200State</State>
<StreamLocation>^WS.DE.DE041023200S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
