Class WS.DE.DE041003300 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Parameter Category = "体格检查";

Parameter Description = "可疑佝偻病症状代码";

Parameter Format = "N1";

Parameter ValueSet;

Parameter WSDT = "S3";

Property Value;

Storage Default
{
<Data name="DE041003300State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE041003300State</State>
<StreamLocation>^WS.DE.DE041003300S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
