Class WS.DE.DE041015400 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV04.10.018");

Parameter Category = "体格检查";

Parameter Description = "前囟张力代码";

Parameter Format = "N1";

Parameter ValueSet = "CV04.10.018";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE041015400State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE041015400State</State>
<StreamLocation>^WS.DE.DE041015400S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
