Class WS.DE.DE051014300 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As %Boolean;

Parameter Category = "医学评估";

Parameter Description = "陈述内容可靠标识";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Storage Default
{
<Data name="DE051014300State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE051014300State</State>
<StreamLocation>^WS.DE.DE051014300S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
