Class WS.DE.DE060024500 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As %Boolean;

Parameter Category = "计划与干预";

Parameter Description = "使用中医技术标志";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Storage Default
{
<Data name="DE060024500State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060024500State</State>
<StreamLocation>^WS.DE.DE060024500S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
