Class WS.DE.DE060014200 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.109");

Parameter Category = "计划与干预";

Parameter Description = "乙肝疫苗接种剂量";

Parameter Format = "N1";

Parameter ValueSet = "CV06.00.109";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060014200State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060014200State</State>
<StreamLocation>^WS.DE.DE060014200S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
