Class WS.DE.DE060000300 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.119");

Parameter Category = "计划与干预";

Parameter Description = "艾滋病抗病毒治疗终止原因代码";

Parameter Format = "N1";

Parameter ValueSet = "CV06.00.119";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060000300State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060000300State</State>
<StreamLocation>^WS.DE.DE060000300S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
