Class WS.DE.DE060015500 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As %Boolean;

Parameter Category = "计划与干预";

Parameter Description = "知情同意管理标志";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Storage Default
{
<Data name="DE060015500State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060015500State</State>
<StreamLocation>^WS.DE.DE060015500S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
