Class WS.DE.DE060005900 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.204");

Parameter Category = "计划与干预";

Parameter Description = "戒烟方法类别代码";

Parameter Format = "N2";

Parameter ValueSet = "CV06.00.204";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060005900State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060005900State</State>
<StreamLocation>^WS.DE.DE060005900S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
