Class WS.DE.DE060014000 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.111");

Parameter Category = "计划与干预";

Parameter Description = "乙肝抗病毒治疗终止原因";

Parameter Format = "N2";

Parameter ValueSet = "CV06.00.111";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060014000State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060014000State</State>
<StreamLocation>^WS.DE.DE060014000S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
