Class WS.DE.DE060018000 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Parameter Category = "计划与干预";

Parameter Description = "辨证施护标志";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Property Value As %Boolean;

Storage Default
{
<Data name="DE060018000State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060018000State</State>
<StreamLocation>^WS.DE.DE060018000S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
