Class WS.DE.DE060006800 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.114");

Parameter Category = "计划与干预";

Parameter Description = "抗结核化疗方案代码";

Parameter Format = "N1";

Parameter ValueSet = "CV06.00.114";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060006800State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060006800State</State>
<StreamLocation>^WS.DE.DE060006800S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
