Class WS.DE.DE060007800 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As %Boolean;

Parameter Category = "计划与干预";

Parameter Description = "美沙酮维持治疗标志";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Storage Default
{
<Data name="DE060007800State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060007800State</State>
<StreamLocation>^WS.DE.DE060007800S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
