Class WS.DE.DE060015800 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.205");

Parameter Category = "计划与干预";

Parameter Description = "职业性放射性疾病处理类别代码";

Parameter Format = "N2";

Parameter ValueSet = "CV06.00.205";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060015800State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060015800State</State>
<StreamLocation>^WS.DE.DE060015800S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
