Class WS.DE.DE060008500 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.105");

Parameter Category = "计划与干预";

Parameter Description = "皮下埋植剂埋植时期代码";

Parameter Format = "N1";

Parameter ValueSet = "CV06.00.105";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060008500State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060008500State</State>
<StreamLocation>^WS.DE.DE060008500S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
