Class WS.DE.DE060018600 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Property Value As WS.DT.CodedString(ValueSet = "CV06.00.227");

Parameter Category = "计划与干预";

Parameter Description = "操作部位编码";

Parameter Format = "N2";

Parameter ValueSet = "CV06.00.227";

Parameter WSDT = "S3";

Storage Default
{
<Data name="DE060018600State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060018600State</State>
<StreamLocation>^WS.DE.DE060018600S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
