Class WS.DE.DE060006300 Extends WS.DE.Base [ Language = objectscript, Not ProcedureBlock ]
{

Parameter Category = "计划与干预";

Parameter Description = "开设健康教育课程标志";

Parameter Format;

Parameter ValueSet;

Parameter WSDT = "L";

Property Value As %Boolean;

Storage Default
{
<Data name="DE060006300State">
<Value name="1">
<Value>Value</Value>
</Value>
</Data>
<State>DE060006300State</State>
<StreamLocation>^WS.DE.DE060006300S</StreamLocation>
<Type>%Storage.Serial</Type>
}

}
